### ISSUE TITLE
README needs updating

### ISSUE THREAD

**Issue by IvanDyankov** [VirtuOz/node-dynamic-module-loader#15]
Great work with this module, you saved me a LOT of time!

Only one minor issue is that your README instructions need updating.

For example:

```
// Set the download directory.  Default is ./downloads
dynamicModuleLoader.setDownloadDir(path.normalize("/some/accessible/location/downloads"));
```

Returns an error saying that `setDownloadDir` is not a function.

So can you please clarify that those properties you can pass via a `config` object.
(Apologies, I don't have much time to raise the PR myself.)

Kind Regards,
Ivan

**Comment by kevandunsmore** [comment]
Yes, you can pass those using a config option to the constructor of DynamicModuleLoader. See here: 

https://github.com/VirtuOz/node-dynamic-module-loader/blob/master/lib/dml_config.js#L24

For example:

var dml = new DynamicModuleLoader({
    downloadDir: '/somewhere/over/the/rainbow'
});

I'll update the README.md file to reflect this.

**Comment by jenskdsgn** [comment]
> Returns an error saying that setDownloadDir is not a function.

I am having the same issue. (v 1.3.2)

**Comment by sbellone** [comment]
README updated. Actually you can also access and modify all properties through the `settings` field:
```javascript
dynamicModuleLoader.settings.downloadDir = path.normalize("/some/accessible/location/downloads");
```
I've specified that as well. Thanks for reporting!
